# Use this file to configure the Affiance hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/l8on/affiance/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/affiance/tree/master/lib/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/l8on/affiance#configuration
#
# Uncomment the following lines to make the configuration take effect.

CommitMsg:
  ALL:
    requiresFiles: false
    quiet: false

  CapitalizedSubject:
    enabled: true
    description: 'Check subject capitalization'

  EmptyMessage:
    enabled: true
    description: 'Check for empty commit message'
    quiet: true

PreCommit:
  ALL:
    quiet: false

  EsLint:
    enabled: true

  MergeConflicts:
    enabled: false
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  NpmUpdate: # Check if node modules are up to date on checkout.
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes
